"use client";

import * as React from "react";
import { Button } from "@/components/ui/button";
import { SparklesIcon, Loader2Icon, XIcon } from "lucide-react";

interface AISummarizeButtonProps {
    content: string;
    title: string;
    onSummaryChange: (summary: string | null) => void;
    isActive: boolean;
}

export function AISummarizeButton({ content, title, onSummaryChange, isActive }: AISummarizeButtonProps) {
    const [isLoading, setIsLoading] = React.useState(false);

    const handleSummarize = async () => {
        if (isActive) {
            // Turn off summary mode
            onSummaryChange(null);
            return;
        }

        setIsLoading(true);

        // Simulate AI processing
        await new Promise(resolve => setTimeout(resolve, 2000));

        // Mockup AI summary
        const mockSummary = `## AI Summary

This article provides an in-depth analysis of **${title}**, examining the key developments and their implications.

**Key Points:**

- The main argument centers around emerging trends and their potential impact on the industry
- Several experts weigh in with their perspectives on future developments
- The conclusion suggests that significant changes are on the horizon
- New research data supports the evolving landscape in this field

**Main Takeaway:**

This piece presents a balanced view, incorporating multiple perspectives while highlighting the most critical factors. The author emphasizes the importance of staying informed and adapting to rapid changes in the sector.

**Reading Time Saved:** ~3 minutes

---
*This summary was generated by AI for quick reading.*`;

        onSummaryChange(mockSummary);
        setIsLoading(false);
    };

    return (
        <Button
            variant={isActive ? "default" : "outline"}
            size="sm"
            onClick={handleSummarize}
            disabled={isLoading}
            className={isActive
                ? "gap-1.5 bg-violet-500 hover:bg-violet-600 text-white"
                : "gap-1.5 border-violet-500/30 text-violet-500 hover:bg-violet-500/10 hover:text-violet-500"
            }
        >
            {isLoading ? (
                <>
                    <Loader2Icon className="h-3.5 w-3.5 animate-spin" />
                    Summarizing...
                </>
            ) : isActive ? (
                <>
                    <XIcon className="h-3.5 w-3.5" />
                    Show Full Article
                </>
            ) : (
                <>
                    <SparklesIcon className="h-3.5 w-3.5" />
                    AI Summary
                </>
            )}
        </Button>
    );
}
